### ISSUE TITLE
Chyba a QoL vylepšení

### ISSUE THREAD

**Issue by rancor1223** [ServalTheServal/CZUWDAT#1]
Je tam několik duplicitních otázek bez textu otázky na řádcích 2979, 3007 a 3021.

----

Dál bych navrhnul malý QoL vylepšení. U tech checkboxů vyměň <span> za <label> ať se nemusíme trefovat na ten mrňavej checkbox. Pak bude klikatelnej celej ten řádek.

Tady už jsem to udělal (nahradit tim řádky 90-156) a zdá se že to funguje správně. 
https://pastebin.com/raM7U6TH

**Comment by ServalTheServal** [comment]
Super, díky 😄 Ty checkboxy jsou trochu otravný, sám jsem přemýšlel nad tím, že bych to opravil, ale byl jsem líný 😆

**Comment by ServalTheServal** [comment]
Nahozena upravená verze, díky 😃
